
project_id = "tsjdsbxgottssqqlzfxl"

[functions.login-with-cpf]
verify_jwt = false

[functions.create-user-with-cpf]
verify_jwt = false

[functions.init-master-user]
verify_jwt = false

[postgres_functions]
check_user_role = { schema = "public" }
get_user_role = { schema = "public", replace = true }
is_admin_user = { schema = "public", replace = true }
is_master_user = { schema = "public", replace = true }
ensure_user_permissions = { schema = "public", replace = true }
