
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tsjdsbxgottssqqlzfxl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzamRzYnhnb3R0c3NxcWx6ZnhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1ODM3NDgsImV4cCI6MjA2MDE1OTc0OH0.3WVd3cIBxyUlJGBjCzwLs5YY14xC6ZNtMbb5zuxF0EY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: false,
    flowType: 'pkce'
  }
});

// Add type conversion helpers to handle metadata and additional properties
export const processUserProfile = (profile: any) => {
  if (!profile) return null;
  
  // Process metadata for additional properties
  const metadata = profile.raw_user_meta_data || {};
  
  // Process permissions to ensure they have all the required properties
  const processedPermissions = profile.permissions?.map((permission: any) => {
    return {
      ...permission,
      // Add missing permission properties used in the app
      can_create_user: permission.can_create_user || false,
      can_edit_user_status: permission.can_edit_user_status || false,
      can_set_user_permissions: permission.can_set_user_permissions || false,
      can_create_section: permission.can_create_section || false,
      can_edit_section: permission.can_edit_section || false,
      can_delete_section: permission.can_delete_section || false,
      can_create_field: permission.can_create_field || false,
      can_edit_field: permission.can_edit_field || false,
      can_delete_field: permission.can_delete_field || false,
      can_fill_field: permission.can_fill_field || false,
      can_sign: permission.can_sign || false,
      can_insert_logo: permission.can_insert_logo || false,
      can_insert_photo: permission.can_insert_photo || false,
      can_save: permission.can_save || false,
      can_save_as: permission.can_save_as || false,
      can_download: permission.can_download || false,
      can_open: permission.can_open || false,
      can_print: permission.can_print || false,
      can_edit_document: permission.can_edit_document || false,
      can_cancel_document: permission.can_cancel_document || false,
      can_view: permission.can_view || false
    };
  });
  
  return {
    ...profile,
    // Ensure these properties exist
    is_admin: profile.is_admin || metadata.is_admin || false,
    is_master: profile.is_master || metadata.is_master || false,
    // Replace permissions with processed permissions
    permissions: processedPermissions || []
  };
};
